package br.acc.banco.models.enums;

public enum TipoOperacao{
	SAQUE,DEPOSITO,TRANSFERENCIA,COMPRA,PIX,
	PARCELA_EMPRESTIMO,RECEBEU_PIX,RECEBEU_TRANSFERENCIA, PARCELA_SEGURO,RESGATOU_SEGURO,FEZ_EMPRESTIMO;
}
	